import type { StyleDef, StyleKey } from "./types";

export const STYLES: Record<StyleKey, StyleDef> = {
  vintage_film: {
    key: "vintage_film",
    name: "复古胶片",
    english: "Vintage Film",
    description: "颗粒感、暖黄、低饱和,像翻一本九零年代旅居杂志。",
    palette: ["#C7A07A", "#7A5230", "#F4E6CE"],
    vibe: "怀旧、慢节奏、文学感",
    titlePrefixes: ["翻到这家", "藏在", "胶片里的"],
    titleSuffixes: ["像被时间留下的", "一帧老电影", "慢一拍的住法"],
    toneAdjectives: ["温润", "怀旧", "缓慢", "厚重"],
    emojiSet: ["📷", "🍂", "🎞️", "✨"],
    coverHeadline: "胶片里的住宿日记",
  },
  korean_cream: {
    key: "korean_cream",
    name: "韩系奶油",
    english: "Korean Cream",
    description: "高明度、奶白米色、柔焦,像首尔民宿封面图。",
    palette: ["#F8EDE0", "#E8C7A6", "#C58B6F"],
    vibe: "干净、奶系、温柔",
    titlePrefixes: ["奶系入住", "白白软软的", "奶油色的"],
    titleSuffixes: ["像踩进云朵", "巨治愈", "想再住一晚"],
    toneAdjectives: ["柔和", "温润", "干净", "奶系"],
    emojiSet: ["🤍", "☁️", "🥐", "✨"],
    coverHeadline: "Cream Stay｜软软的一晚",
  },
  japanese_clean: {
    key: "japanese_clean",
    name: "日系清透",
    english: "Japanese Clean",
    description: "高光通透、原木+亚麻、留白多。",
    palette: ["#EDE7DA", "#A99372", "#DCE3DA"],
    vibe: "清淡、原木、自然光",
    titlePrefixes: ["很日杂感的", "清清淡淡", "原木味的"],
    titleSuffixes: ["像京都散步", "一杯抹茶的住法", "无负担入住"],
    toneAdjectives: ["清透", "克制", "干净", "自然"],
    emojiSet: ["🍵", "🌿", "🪵", "☁️"],
    coverHeadline: "晴れた日｜清透感住宿",
  },
  high_minimal: {
    key: "high_minimal",
    name: "高级极简",
    english: "High Minimal",
    description: "黑白灰大色块、留白、克制配色。",
    palette: ["#1A1A1A", "#9A9A9A", "#F1F1F1"],
    vibe: "克制、建筑感、低调",
    titlePrefixes: ["低调入住", "克制美学", "无声入住"],
    titleSuffixes: ["把噪声关在门外", "高级感拉满", "可以发朋友圈那种"],
    toneAdjectives: ["冷静", "克制", "高级", "结构感"],
    emojiSet: ["◼️", "◻️", "✦"],
    coverHeadline: "STAY / MINIMAL",
  },
  travel_mag: {
    key: "travel_mag",
    name: "旅行杂志",
    english: "Travel Magazine",
    description: "国家地理感、大跨页、强排版、地理标识。",
    palette: ["#1E3A2B", "#D7B26D", "#F2EEE5"],
    vibe: "杂志感、目的地视角、有信息量",
    titlePrefixes: ["这一站", "目的地", "封面级"],
    titleSuffixes: ["值得专程一趟", "可以收藏的住法", "旅行清单 +1"],
    toneAdjectives: ["饱满", "权威", "故事感", "信息感"],
    emojiSet: ["🌍", "📰", "📍", "🧭"],
    coverHeadline: "ISSUE｜值得专程的酒店",
  },
  french_romance: {
    key: "french_romance",
    name: "法式浪漫",
    english: "French Romance",
    description: "复古花纹、亚麻奶油、烛光感,像左岸下午。",
    palette: ["#F3E6D8", "#B07A6B", "#8C3A4A"],
    vibe: "浪漫、慵懒、复古",
    titlePrefixes: ["像住进巴黎", "法式入住", "微醺的"],
    titleSuffixes: ["一次浪漫越权", "想点一杯香槟", "不舍得退房"],
    toneAdjectives: ["浪漫", "慵懒", "细腻", "微醺"],
    emojiSet: ["🥂", "🌹", "🕯️", "🤍"],
    coverHeadline: "Une nuit｜法式浪漫一晚",
  },
  moody_premium: {
    key: "moody_premium",
    name: "暗调高级",
    english: "Moody Premium",
    description: "深色背景、低饱和高光、电影质感。",
    palette: ["#16161A", "#3E3845", "#C2A076"],
    vibe: "电影感、夜晚、低声诉说",
    titlePrefixes: ["夜色里的", "藏在城市背面的", "低调到不发声的"],
    titleSuffixes: ["像看了一部电影", "夜晚的最佳藏身处", "灯光会替你说话"],
    toneAdjectives: ["沉静", "电影感", "深度", "夜晚"],
    emojiSet: ["🌙", "🥃", "✨", "🎬"],
    coverHeadline: "After Dark｜夜色入住",
  },
  ins_life: {
    key: "ins_life",
    name: "INS生活感",
    english: "INS Life",
    description: "明亮日常感、自然光、随手拍。",
    palette: ["#FDF6EC", "#F2B6A6", "#5B7C99"],
    vibe: "日常、清新、可爱",
    titlePrefixes: ["巨日常", "随手一拍就好看", "把生活搬进"],
    titleSuffixes: ["日常感拉满", "随便住都出片", "想留下来生活一周"],
    toneAdjectives: ["轻盈", "明亮", "随手", "可爱"],
    emojiSet: ["☀️", "🍞", "🌷", "🤍"],
    coverHeadline: "Daily｜生活感入住",
  },
  xhs_burst: {
    key: "xhs_burst",
    name: "小红书爆款封面",
    english: "XHS Viral Cover",
    description: "大字标题、强对比、贴纸感、表情符号。",
    palette: ["#FFEDED", "#FF4D5E", "#1F1F1F"],
    vibe: "信息量、对比强、抓眼球",
    titlePrefixes: ["真的会爱上！", "蹲到了", "求求你们一定要住"],
    titleSuffixes: ["巨出片！！", "性价比天花板", "封神入住"],
    toneAdjectives: ["夸张", "热情", "信息感", "爆款体"],
    emojiSet: ["🚨", "🔥", "📍", "✨", "🤍"],
    coverHeadline: "蹲到了！这家必须冲",
  },
  lux_hotel: {
    key: "lux_hotel",
    name: "轻奢酒店",
    english: "Luxe Hotel",
    description: "金属香槟金、墨绿、丝绒、低调奢华。",
    palette: ["#1B2A22", "#C9A35B", "#F2EBDC"],
    vibe: "克制、轻奢、品质",
    titlePrefixes: ["不动声色的", "藏在城市里的", "懂的人才会订的"],
    titleSuffixes: ["一晚封神", "把奢华藏进细节", "值得为它专程"],
    toneAdjectives: ["质感", "克制", "细节", "稳"],
    emojiSet: ["🥂", "✨", "🛎️", "🤍"],
    coverHeadline: "Quiet Luxury｜轻奢入住",
  },
  city_pop: {
    key: "city_pop",
    name: "都市霓虹",
    english: "City Pop",
    description: "霓虹冷调、玻璃幕墙、夜晚都市。",
    palette: ["#0E1A2B", "#2BB1FF", "#FF5BA7"],
    vibe: "城市、夜晚、能量",
    titlePrefixes: ["市中心藏着", "霓虹里的", "落地窗装下整座"],
    titleSuffixes: ["夜景封神", "拍照不用修", "上班族的回血点"],
    toneAdjectives: ["都市", "锐利", "霓虹", "能量"],
    emojiSet: ["🌃", "🪩", "🍸", "✨"],
    coverHeadline: "City Lights｜都市夜住",
  },
  warm_documentary: {
    key: "warm_documentary",
    name: "暖色纪实",
    english: "Warm Documentary",
    description: "暖色调记录、生活流、低饱和故事感。",
    palette: ["#E8C9A3", "#A66A4A", "#3C2A1E"],
    vibe: "纪实、暖、故事",
    titlePrefixes: ["在这里慢下来", "记一次", "认真住过的"],
    titleSuffixes: ["像一段被收藏的故事", "值得被记住", "想第二次回来"],
    toneAdjectives: ["叙事", "温暖", "诚实", "克制"],
    emojiSet: ["📖", "🤍", "☀️"],
    coverHeadline: "Stay & Remember",
  },
};

export const STYLE_LIST: StyleDef[] = Object.values(STYLES);
